#!/usr/bin/bash
gnuplot plot_all_time_breakdown_16x.gnu
gnuplot plot_all_time_breakdown_16x_webspam_epsilon.gnu
gnuplot plot_all_time_breakdown_16x_webspam_epsilon_log.gnu
gnuplot plot_all_time_breakdown_log_16x_c=1,2,4,8.gnu
gnuplot plot_all_time_breakdown_log_16x.gnu
gnuplot plot_all_time_log_16x.gnu
